# Generated by Django 5.1.1 on 2024-09-18 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_doctorprofile_user_alter_patientprofile_user"),
        ("appointments", "0005_doctorprofile_alter_appointment_doctor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.doctorprofile"
            ),
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="user",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.patientprofile",
            ),
        ),
        migrations.DeleteModel(
            name="DoctorProfile",
        ),
        migrations.DeleteModel(
            name="PatientProfile",
        ),
    ]
