# Generated by Django 5.1.1 on 2024-09-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0006_alter_appointment_doctor_remove_patientprofile_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="chat_service_sid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="room_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
